export const optionsColorsBadge = [
  { value: "#d9f99d", badge: "#a3e635" , label: "Lime" },
  { value: "#a5f3fc", badge: "#22d3ee" , label: "Cyan" },
  { value: "#bfdbfe", badge: "#3b82f6" , label: "Blue" },
  { value: "#ddd6fe", badge: "#8b5cf6" , label: "Violet" },
  { value: "#fecdd3", badge: "#f87171" , label: "Red" },
  { value: "#f5d0fe", badge: "#f472b6" , label: "Fuchsia" },
  { value: "#fde68a", badge: "#fbbf24" , label: "Amber" },
  { value: "#fef08a", badge: "#facc15" , label: "Yellow" },
  { value: "#bbf7d0", badge: "#6ee7b7" , label: "Green" },
  { value: "#fbcfe8", badge: "#f472b6" , label: "Pink" },
  { value: "#c7d2fe", badge: "#667eea" , label: "Indigo" },
  { value: "#e9d5ff", badge: "#8b5cf6" , label: "Purple" },
  { value: "#99f6e4", badge: "#4ade80" , label: "Teal" },
  { value: "#e5e7eb", badge: "#d1d5db" , label: "Gray" },
  { value: "#bae6fd", badge: "#0ea5e9" , label: "Sky" },
  { value: "#a7f3d0", badge: "#34d399" , label: "Emerald" },
];

export const optionsTags = [
  { value: "compras", label: "Compras" },
  { value: "salud", label: "Salud" },
  { value: "amor", label: "Amor" },
  { value: "casa", label: "Casa" },
  { value: "viaje", label: "Viaje" },
  { value: "comida", label: "Comida" },
  { value: "gym", label: "Gym" },
  { value: "estudios", label: "Estudios" },
  { value: "trabajo", label: "Trabajo" },
  { value: "limpieza", label: "Limpieza" },
  { value: "cocina", label: "Cocina" },
  { value: "ejercicio", label: "Ejercicio" },
  { value: "lectura", label: "Lectura" },
  { value: "descanso", label: "Descanso" },
  { value: "meditacion", label: "Meditacion" },
  { value: "musica", label: "Música" },
  { value: "paseo", label: "Paseo" },
  { value: "cine", label: "Cine" },
  { value: "series", label: "Series" },
  { value: "juegos", label: "Juegos" },
  { value: "deportes", label: "Deportes" },
  { value: "amigos", label: "Amigos" },
  { value: "familia", label: "Familia" },
];